name: nix-rebuild-analyser-test
version: 0.0.0.0
license: GPL

dependencies:
- base >= 4.7 && < 5

tests:
  nix-rebuild-analyser-test:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sydtest
    - nix-rebuild-analyser
    - aeson
    - aeson-pretty
    - bytestring
    - monad-logger
    - path
    - path-io
    - typed-process
